// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDojbYswNh-qNQEIx0r9zQ2oF_0aBkgZ9I',
    appId: '1:684124894729:web:f3e1839ea762e17572aad8',
    messagingSenderId: '684124894729',
    projectId: 'banlieuwest-a97e5',
    authDomain: 'banlieuwest-a97e5.firebaseapp.com',
    databaseURL: 'https://banlieuwest-a97e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banlieuwest-a97e5.appspot.com',
    measurementId: 'G-FNEFF3S1SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBnPglOswN-hHbe616ditqE21BAP-SpbU',
    appId: '1:684124894729:android:254c9e96f1a87a2e72aad8',
    messagingSenderId: '684124894729',
    projectId: 'banlieuwest-a97e5',
    databaseURL: 'https://banlieuwest-a97e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banlieuwest-a97e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdz_81uc_B-WJoNrnhtpnSl1IwYx0wxM',
    appId: '1:684124894729:ios:e04796c94fbdc39272aad8',
    messagingSenderId: '684124894729',
    projectId: 'banlieuwest-a97e5',
    databaseURL: 'https://banlieuwest-a97e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banlieuwest-a97e5.appspot.com',
    iosBundleId: 'com.example.goaldigger2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdz_81uc_B-WJoNrnhtpnSl1IwYx0wxM',
    appId: '1:684124894729:ios:e04796c94fbdc39272aad8',
    messagingSenderId: '684124894729',
    projectId: 'banlieuwest-a97e5',
    databaseURL: 'https://banlieuwest-a97e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banlieuwest-a97e5.appspot.com',
    iosBundleId: 'com.example.goaldigger2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDojbYswNh-qNQEIx0r9zQ2oF_0aBkgZ9I',
    appId: '1:684124894729:web:1b85c9d9e71d75d772aad8',
    messagingSenderId: '684124894729',
    projectId: 'banlieuwest-a97e5',
    authDomain: 'banlieuwest-a97e5.firebaseapp.com',
    databaseURL: 'https://banlieuwest-a97e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banlieuwest-a97e5.appspot.com',
    measurementId: 'G-G8VF35BVZF',
  );
}
